# generated by CodingAgentTools — the plugin itself lives in this repo
import { tool } from "@opencode-ai/plugin"
import { plugin } from "/Users/kohei/Workspace/CodingAgentTools/opencode/plugin/goal.js"

export const Plugin = plugin({ tool })
